import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';

const RAW_DIR = path.join('fixtures', 'raw-dom');
const EXPECTED_MD_DIR = path.join('fixtures', 'expected-md');
const EXPECTED_JSON_DIR = path.join('fixtures', 'expected-json');

function baseName(fileName: string): string {
  return fileName.replace(/\.[^.]+$/, '');
}

async function main(): Promise<void> {
  await mkdir(EXPECTED_MD_DIR, { recursive: true });
  await mkdir(EXPECTED_JSON_DIR, { recursive: true });

  const rawFiles = await readdir(RAW_DIR);
  const fixtureFiles = rawFiles.filter((file) => file.endsWith('.html'));

  if (fixtureFiles.length === 0) {
    console.log('No raw fixtures found.');
    return;
  }

  for (const fileName of fixtureFiles) {
    const fixtureId = baseName(fileName);
    const rawPath = path.join(RAW_DIR, fileName);
    const markdownPath = path.join(EXPECTED_MD_DIR, `${fixtureId}.md`);
    const jsonPath = path.join(EXPECTED_JSON_DIR, `${fixtureId}.json`);

    const rawHtml = await readFile(rawPath, 'utf8');

    const markdownTemplate = `# Fixture ${fixtureId}\n\n<!-- Generated by scripts/collect-fixtures.ts -->\n\nRaw length: ${rawHtml.length} characters.\n`;
    await writeFile(markdownPath, markdownTemplate, 'utf8');

    const jsonTemplate = {
      fixtureId,
      source: 'chatgpt-atlas',
      generatedBy: 'scripts/collect-fixtures.ts',
      rawLength: rawHtml.length,
      turns: []
    };
    await writeFile(jsonPath, `${JSON.stringify(jsonTemplate, null, 2)}\n`, 'utf8');

    console.log(`Collected ${fixtureId}`);
  }
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
